const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {decode,snapshot,prepare}=require('../eva1-import.js'),aliases=require('../eva1-hero-ids.js');
const text=s=>{const b=Buffer.from(s);return Buffer.concat([Buffer.from([b.length]),b]);};
const value=x=>{if(Array.isArray(x))return Buffer.concat([Buffer.from([10]),...x.map(value),Buffer.from([255])]);if(x&&typeof x==='object')return Buffer.concat([Buffer.from([11]),map(x)]);if(typeof x==='string')return Buffer.concat([Buffer.from([8]),text(x)]);if(Number.isInteger(x)){if(x>=0&&x<=255)return Buffer.from([3,x]);const b=Buffer.alloc(5);b[0]=5;b.writeInt32LE(x,1);return b;}if(typeof x==='boolean')return Buffer.from([x?2:1]);return Buffer.from([0]);};
const map=x=>Buffer.concat([...Object.entries(x).flatMap(([k,v])=>[text(k),value(v)]),Buffer.from([255])]);
const save=(data,operations=[])=>{const root=map(data),len=Buffer.alloc(4);len.writeUInt32LE(root.length);return Buffer.concat([Buffer.from([3,1]),value('v389.0'),map({operations}),len,root]);};
const fixture={profileState:{name:'Test <account>'},heroesState:{ownedHeroesCollection:{heroIdToOwnedData:{ghost_he_gui:{a:[{id:1,s:'l90,a4,s8,b2',t:25,f:3,c:[{id:'cute',s:'l70,a4,s8'}]},{id:2,s:'l80,a4,s8,b1',t:921}]},ice_god_vela:{b:[3]},unknown_new_hero:{a:[{id:4,s:'l1,a1,s1'}]}},guestOriginToOwnedInfos:{GuestIP:[{key:'999',hd:{id:'guest'}}]}},teams:{main_1:{tm:[{hid:'1',tid:'54'},{hid:'empty',tid:'default'}],bat:[]}}},troopsState:{savedOwnedIdToTroopDefinitions:{54:{td:{id:'test_troop',lvl:30}}}},inventoryState:{inventory:{item_ghost_he_gui_costume_cute:1,item_ghost_he_gui_costume_unknown:1}},gems:10000,shop:{secret:'not-roster'}};
const bytes=save(fixture),decoded=decode(bytes),snap=snapshot(decoded),catalog=[{name:'He Gui'},{name:'Vela'}];
assert.equal(decoded.clientVersion,'v389.0');assert.equal(snap.heroes.length,4);assert.equal(snap.heroes[0].unlockedTalentNodes,2);assert.equal(snap.heroes[0].talentCountConflict,true);assert.equal(snap.heroes[1].unlockedTalentNodes,25);assert.equal(snap.heroes[2].level,null);assert.equal(snap.heroes[0].costumes[0].limitBreak,0);assert.equal(snap.accountName,'Test <account>');assert(!('gems' in snap));assert(!('shop' in snap));
const plan=prepare(snap,catalog,aliases);assert.equal(plan.matchedInstances,3);assert.equal(plan.own['He Gui'].n,2);assert.equal(plan.own['He Gui'].c,2);assert.equal(plan.unmatched[0].definitionId,'unknown_new_hero');assert.equal(plan.own.Vela.instances[0].level,null);
const repeat=prepare(snap,catalog,aliases,plan.own);assert.equal(repeat.own['He Gui'].n,2);
const old={'He Gui':{instances:[{instanceId:'2'},{instanceId:'1'}],ps:[1222,1111],path:'defense',note:'Keep me'}};
const refresh=prepare(snap,catalog,aliases,old);assert.deepEqual(refresh.own['He Gui'].ps,[1111,1222]);assert.equal(refresh.own['He Gui'].path,'defense');assert.equal(refresh.own['He Gui'].note,'Keep me');
const manual=prepare(snap,catalog,aliases,{}, {unknown_new_hero:'Vela'});assert.equal(manual.unmatched.length,0);assert.equal(manual.own.Vela.n,2);assert.throws(()=>prepare(snap,catalog,aliases,{}, {unknown_new_hero:'Not a hero'}));
for(const n of [0,10,bytes.length-1])assert.throws(()=>decode(bytes.subarray(0,n)));assert.throws(()=>decode(save(fixture,[{unsupported:true}])));
const bad=Buffer.from(bytes);bad[0]=0;assert.throws(()=>decode(bad));
const duplicate=structuredClone(fixture);duplicate.heroesState.ownedHeroesCollection.heroIdToOwnedData.ghost_he_gui.a[1].id=1;assert.throws(()=>snapshot(decode(save(duplicate))));
for(const file of ['index.html','app_template.html']){const html=fs.readFileSync(require('path').join(__dirname,'..',file),'utf8');new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('__HERO_DATA__','[]'));assert(html.includes('id="eva1Import"'));assert(html.includes('src="eva1-ui.js"'));}
for(const file of ['eva1-import.js','eva1-ui.js','eva1-hero-ids.js'])new vm.Script(fs.readFileSync(require('path').join(__dirname,'..',file),'utf8'));
if(process.argv[2]){const real=snapshot(decode(fs.readFileSync(process.argv[2]))),cat=JSON.parse(fs.readFileSync(require('path').join(__dirname,'../heroes_full.json'))),actual=prepare(real,cat,aliases);assert(actual.totalInstances>0);console.log('Private fixture decoded locally. Matched '+actual.matchedInstances+' of '+actual.totalInstances+' instances; no save data is committed.');}
console.log('EVA1 tests passed: decoding, corruption rejection, duplicates, costumes, unknown IDs, refresh, per-instance powers, snapshot scope, and app syntax.');
